config/routes.rb
BootstrapStarter::Application.routes.draw do

	#--------------------------------
	# all resources should be within the scope block below
	#--------------------------------
	scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

		match '/admin', :to => 'admin#index', :as => :admin, :via => :get
		devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'},
											 :controllers => {:omniauth_callbacks => "omniauth_callbacks"}


		namespace :admin do
      resources :organizations
      resources :projects do
        collection do
          get 'migrate'
          post 'migrate'
        end
      end
      resources :groups
      resources :stages
      resources :project_types
      resources :pages
			resources :users
		end

    resources :timestamps

    # summary pages
    match '/summary', :to => 'summary#index', :as => :summary, :via => :get
    match '/summary/user', :to => 'summary#user', :as => :summary_user, :via => :get
    match '/summary/project', :to => 'summary#project', :as => :summary_project, :via => :get
    match '/summary/project_date_map/:id', :to => 'summary#project_date_map', :as => :summary_project_date_map, :via => :get, format: :json
    match '/summary/user_date_map/:id', :to => 'summary#user_date_map', :as => :summary_user_date_map, :via => :get, format: :json
    match '/summary/date', :to => 'summary#date', :as => :summary_date, :via => :get

		root :to => 'root#index'
	  match "*path", :to => redirect("/#{I18n.default_locale}") # handles /en/fake/path/whatever
	end

	match '', :to => redirect("/#{I18n.default_locale}") # handles /
	match '*path', :to => redirect("/#{I18n.default_locale}/%{path}") # handles /not-a-locale/anything

end

app/controllers/admin/project_types_controller.rb
class Admin::ProjectTypesController < ApplicationController
  before_filter :authenticate_user!
  before_filter do |controller_instance|
    controller_instance.send(:valid_role?, User::ROLES[:site_admin])
  end
  before_filter do |controller_instance|
    controller_instance.send(:is_active_user?)
  end

  # GET /project_types
  # GET /project_types.json
  def index
    @project_types = ProjectType.sorted

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @project_types }
    end
  end

  # GET /project_types/1
  # GET /project_types/1.json
  def show
    @project_type = ProjectType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project_type }
    end
  end

  # GET /project_types/new
  # GET /project_types/new.json
  def new
    @project_type = ProjectType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project_type }
    end
  end

  # GET /project_types/1/edit
  def edit
    @project_type = ProjectType.find(params[:id])
  end

  # POST /project_types
  # POST /project_types.json
  def create
    @project_type = ProjectType.new(params[:project_type])

    respond_to do |format|
      if @project_type.save
        format.html { redirect_to admin_project_types_path, notice: t('app.msgs.success_created', :obj => t('activerecord.models.project_type')) }
        format.json { render json: @project_type, status: :created, location: @project_type }
      else
        format.html { render action: "new" }
        format.json { render json: @project_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /project_types/1
  # PUT /project_types/1.json
  def update
    @project_type = ProjectType.find(params[:id])

    respond_to do |format|
      if @project_type.update_attributes(params[:project_type])
        format.html { redirect_to admin_project_types_path, notice: t('app.msgs.success_updated', :obj => t('activerecord.models.project_type')) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_types/1
  # DELETE /project_types/1.json
  def destroy
    @project_type = ProjectType.find(params[:id])
    @project_type.destroy

    respond_to do |format|
      format.html { redirect_to admin_project_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/project_types_helper.rb
module ProjectTypesHelper
end

app/views/admin/project_types/_form.html.erb
<%= semantic_form_for [:admin, @project_type] do |f| %>
  <%= f.error_messages %>

  <%= f.inputs do %>
    <%= f.input :name %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
              admin_project_types_path, :class => 'btn btn-default' %>
  <% end %>
<% end %>

app/views/admin/project_types/edit.html.erb
<%- model_class = ProjectType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/project_types/index.html.erb
<%- model_class = ProjectType -%>

<div class="page-header">
  <h1>
    <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %>
    <%= link_to t('.new', :default => t("helpers.links.new")),
      new_admin_project_type_path,
      :class => 'btn btn-primary' %>
    <%= link_to t('helpers.links.admin'), admin_path, :class => 'btn btn-info' %>
  </h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @project_types.each do |project_type| %>
      <tr>
        <td><%= project_type.name %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_project_type_path(project_type), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_project_type_path(project_type),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/project_types/new.html.erb
<%- model_class = ProjectType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/project_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project_type.name %>
</p>


<%= link_to 'Edit', edit_project_type_path(@project_type) %> |
<%= link_to 'Back', project_types_path %>