config/routes.rb
BootstrapStarter::Application.routes.draw do

	#--------------------------------
	# all resources should be within the scope block below
	#--------------------------------
	scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

		match '/admin', :to => 'admin#index', :as => :admin, :via => :get
		devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'},
											 :controllers => {:omniauth_callbacks => "omniauth_callbacks"}


		namespace :admin do
      resources :organizations
      resources :projects do
        collection do
          get 'migrate'
          post 'migrate'
        end
      end
      resources :groups
      resources :stages
      resources :project_types
      resources :pages
			resources :users
		end

    resources :timestamps

    # summary pages
    match '/summary', :to => 'summary#index', :as => :summary, :via => :get
    match '/summary/user', :to => 'summary#user', :as => :summary_user, :via => :get
    match '/summary/project', :to => 'summary#project', :as => :summary_project, :via => :get
    match '/summary/project_date_map/:id', :to => 'summary#project_date_map', :as => :summary_project_date_map, :via => :get, format: :json
    match '/summary/user_date_map/:id', :to => 'summary#user_date_map', :as => :summary_user_date_map, :via => :get, format: :json
    match '/summary/date', :to => 'summary#date', :as => :summary_date, :via => :get

		root :to => 'root#index'
	  match "*path", :to => redirect("/#{I18n.default_locale}") # handles /en/fake/path/whatever
	end

	match '', :to => redirect("/#{I18n.default_locale}") # handles /
	match '*path', :to => redirect("/#{I18n.default_locale}/%{path}") # handles /not-a-locale/anything

end

app/controllers/summary_controller.rb
class SummaryController < ApplicationController
  before_filter :authenticate_user!
  before_filter do |controller_instance|
    controller_instance.send(:valid_role?, User::ROLES[:staff])
  end
  before_filter do |controller_instance|
    controller_instance.send(:is_active_user?)
  end

  def index

  end

  def user
    @users = User.sorted
    records = nil
    begin_at = nil
    last_at = nil
    params[:timestamp_start_at] ||= 1.week.ago.in_time_zone.to_date.to_s
    params[:timestamp_end_at] ||= Time.zone.now.to_date.to_s
    params[:timestamp_user_id] ||= @users.first.id
    @user = @users.select{|x| x.id.to_s == params[:timestamp_user_id].to_s}.first

    if params[:active_projects].present?
      params[:active_projects] = params[:active_projects] == 'true'
    else
      params[:active_projects] = @default_active_projects_value
    end

    params[:active_users] = @default_active_users_value

    records = Timestamp.by_user(params[:timestamp_user_id]).all_stamps(start_at: params[:timestamp_start_at],
                                                                       end_at: params[:timestamp_end_at],
                                                                       active_project: params[:active_projects])
    dates = Timestamp.by_user(params[:timestamp_user_id]).dates

    # in app controller
    load_data_for_charts(records, dates, :projects, :dates, 'charts.summary.user', true, @user.nickname)
    gon.date_map_url = summary_user_date_map_path(id: '__id__')
    gon.date_map_trigger_id = 'timestamp_user_id'
  end

  def user_date_map
    id = params[:id]
    render json: id.present? ? Timestamp.by_user(id).dates : []
  end

  def project
    @projects = Project.sorted_organization
    records = nil
    begin_at = nil
    last_at = nil
    params[:timestamp_start_at] ||= 1.week.ago.in_time_zone.to_date.to_s
    params[:timestamp_end_at] ||= Time.zone.now.to_date.to_s
    params[:timestamp_project_id] ||= @projects.first.id
    @project = @projects.select{|x| x.id.to_s == params[:timestamp_project_id].to_s}.first

    params[:active_projects] = @default_active_projects_value

    if params[:active_users].present?
      params[:active_users] = params[:active_users] == 'true'
    else
      params[:active_users] = @default_active_users_value
    end

    records = Timestamp.by_project(params[:timestamp_project_id]).all_stamps(start_at: params[:timestamp_start_at],
                                                                              end_at: params[:timestamp_end_at],
                                                                              type: Timestamp::SUMMARY[:project],
                                                                              active_user: params[:active_users])
    dates = Timestamp.by_project(params[:timestamp_project_id]).dates

    # in app controller
    load_data_for_charts(records, dates, :users, :dates, 'charts.summary.project', true, @project.full_name)
    gon.date_map_url = summary_project_date_map_path(id: '__id__')
    gon.date_map_trigger_id = 'timestamp_project_id'
  end

  def project_date_map
    id = params[:id]
    render json: id.present? ? Timestamp.by_project(id).dates : []
  end

  def date
    dates = Timestamp.dates
    @dates_formatted = dates.map{|x| [I18n.l(Date.parse(x), format: :chart_axis), x]}
    records = nil
    begin_at = nil
    last_at = nil
    params[:timestamp_date] ||= dates.last
    params[:timestamp_date] = dates.last if params[:timestamp_date].present? && dates.index{|x| x == params[:timestamp_date]}.nil?
    date = dates.select{|x| x == params[:timestamp_date]}.first
    @date_formatted = date.present? ? I18n.l(Date.parse(date), format: :chart_axis) : date
    gon.timestamp_summary_date = date

    if dates.present?
      begin_at = dates.first
      last_at = dates.last
    end

    if params[:active_projects].present?
      params[:active_projects] = params[:active_projects] == 'true'
    else
      params[:active_projects] = @default_active_projects_value
    end

    if params[:active_users].present?
      params[:active_users] = params[:active_users] == 'true'
    else
      params[:active_users] = @default_active_users_value
    end

    records = Timestamp.by_date(params[:timestamp_date]).all_stamps(type: Timestamp::SUMMARY[:date],
                                                                    active_project: params[:active_projects],
                                                                    active_user: params[:active_users])

    # in app controller
    load_data_for_charts(records, dates, :projects, :users, 'charts.summary.date', true, @date_formatted)

  end

end

app/views/summary/date.html.erb
<% title t('.title', date: @date_formatted) %>

  <%= form_tag summary_date_path, method: 'get' do %>
    <div class="row" id="date-pickers">
      <div class="col-xs-3">
        <%= label_tag :timestamp_date, t('.label_date') %>
        <%= text_field_tag :timestamp_date, params[:timestamp_date], size: 14 %>
      </div>
      <div class="col-xs-3 hide-checkbox">
        <% flag = params[:active_projects] %>
        <input type="hidden" name="active_projects" value="<%= flag %>" id="active_projects_value"/>
        <input type="checkbox" value="<%= flag %>"<%= " checked=#{flag}" if flag %> id="active_projects_checkbox"/>
        <%= label_tag :active_projects_checkbox, t('.label_active_projects') %>
      </div>
      <div class="col-xs-3 hide-checkbox">
        <% flag = params[:active_users] %>
        <input type="hidden" name="active_users" value="<%= flag %>" id="active_users_value"/>
        <input type="checkbox" value="<%= flag %>"<%= " checked=#{flag}" if flag %> id="active_users_checkbox"/>
        <%= label_tag :active_users_checkbox, t('.label_active_users') %>
      </div>
      <div class="col-xs-3">
        <%= submit_tag t('.label_submit'), class: 'btn btn-default btn-sm btn-success' %>
      </div>
    </div>
  <% end %>

<% if @timestamps.present? %>


  <!-- Nav tabs -->
  <ul class="nav nav-tabs nav-tabs-mod" role="tablist">
    <li role="presentation" class="active"><a href="#projects" data-id="projects" aria-controls="projects" role="tab" data-toggle="tab"><%= t('tabs.project') %></a></li>
    <li role="presentation"><a href="#activities" data-id="activities" aria-controls="activities" role="tab" data-toggle="tab"><%= t('tabs.activity') %></a></li>
    <li role="presentation"><a href="#table" data-id="table" aria-controls="table" role="tab" data-toggle="tab"><%= t('tabs.table') %></a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active tab-pane-mod" id="projects">
      <div class="pie-chart" id="projects-pie-chart" style="min-height: 500px; margin: 0 auto;"></div>

      <hr />

      <div class="bar-chart" id="projects-bar-chart" style="min-height: 500px; margin: 0 auto;"></div>

    </div>

    <div role="tabpanel" class="tab-pane fade tab-pane-mod" id="activities">
      <div class="pie-chart" id="activities-pie-chart" style="min-height: 500px; margin: 0 auto;"></div>

      <hr />

      <div class="bar-chart" id="activities-bar-chart" style="min-height: 500px; margin: 0 auto;"></div>

    </div>

    <div role="tabpanel" class="tab-pane fade tab-pane-mod" id="table">

      <%= render :partial => 'timestamps/table_notes' %>

    </div>
  </div>


<% else %>

  <p class="alert alert-warning">
    <%= t('.no_hours', date: @date_formatted) %>
  </p>

<% end %>

app/views/summary/index.html.erb
under construction!

app/views/summary/project.html.erb
<% title t('.title', project: @project.full_name) %>

  <%= form_tag summary_project_path, method: 'get' do %>
    <div class="row" id="date-pickers">
      <div class="col-xs-3">
        <%= label_tag :timestamp_project_id, t('.label_project') %>
        <span class="hide-checkbox hide-checkbox-small filter-button">
          <% flag = params[:active_projects] %>
          <input type="hidden" name="active_projects" value="<%= flag %>" id="active_projects_value"/>
          <input type="checkbox" value="<%= flag %>"<%= " checked=#{flag}" if flag %> id="active_projects_checkbox_filter"/>
          <%= label_tag :active_projects_checkbox_filter, t('.label_active_projects') %>
        </span>
        <br />
        <%= select_tag :timestamp_project_id, options_for_select(
          @projects.map{|pr| [pr.full_name, pr.id, { 'data-active': pr.active }.merge(
            @default_active_projects_value && !pr.active ? {disabled: true} : {})]},
          params[:timestamp_project_id])
        %>
      </div>
      <div class="col-xs-2">
        <%= label_tag :timestamp_start_at, t('.label_start') %>
        <br />
        <%= text_field_tag :timestamp_start_at, params[:timestamp_start_at], size: 14 %>
      </div>
      <div class="col-xs-2">
        <%= label_tag :timestamp_end_at, t('.label_end') %>
        <br />
        <%= text_field_tag :timestamp_end_at, params[:timestamp_end_at], size: 14 %>
      </div>
      <div class="col-xs-3 hide-checkbox">
        <% flag = params[:active_users] %>
        <br />
        <input type="hidden" name="active_users" value="<%= flag %>" id="active_users_value"/>
        <input type="checkbox" value="<%= flag %>"<%= " checked=#{flag}" if flag %> id="active_users_checkbox"/>
        <%= label_tag :active_users_checkbox, t('.label_active_users') %>
      </div>
      <div class="col-xs-2">
        <br />
        <%= submit_tag t('.label_submit'), class: 'btn btn-default btn-sm btn-success' %>
      </div>
    </div>
  <% end %>

<% if @timestamps.present? %>


  <!-- Nav tabs -->
  <ul class="nav nav-tabs nav-tabs-mod" role="tablist">
    <li role="presentation" class="active"><a href="#projects" data-id="projects" aria-controls="projects" role="tab" data-toggle="tab"><%= t('tabs.user') %></a></li>
    <li role="presentation"><a href="#activities" data-id="activities" aria-controls="activities" role="tab" data-toggle="tab"><%= t('tabs.activity') %></a></li>
    <li role="presentation"><a href="#table" data-id="table" aria-controls="table" role="tab" data-toggle="tab"><%= t('tabs.table') %></a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active tab-pane-mod" id="projects">
      <div class="pie-chart" id="projects-pie-chart" style="min-height: 500px; margin: 0 auto;"></div>

      <hr />

      <div class="bar-chart" id="projects-bar-chart" style="min-height: 500px; margin: 0 auto;"></div>

    </div>

    <div role="tabpanel" class="tab-pane fade tab-pane-mod" id="activities">
      <div class="pie-chart" id="activities-pie-chart" style="min-height: 500px; margin: 0 auto;"></div>

      <hr />

      <div class="bar-chart" id="activities-bar-chart" style="min-height: 500px; margin: 0 auto;"></div>

    </div>

    <div role="tabpanel" class="tab-pane fade tab-pane-mod" id="table">

      <%= render :partial => 'timestamps/table_notes' %>

    </div>
  </div>

<% else %>

  <p class="alert alert-warning">
    <%= t('.no_hours', project: @project.full_name, start: params[:timestamp_start_at], end: params[:timestamp_end_at]) %>
  </p>

<% end %>

 <% @custom_js = ["pages/summary.js"] %>

app/views/summary/user.html.erb
<% title t('.title', user: @user.nickname) %>

  <%= form_tag summary_user_path, method: 'get' do %>
    <div class="row" id="date-pickers">
      <div class="col-xs-3">
        <%= label_tag :timestamp_user_id, t('.label_user') %>
        <span class="hide-checkbox hide-checkbox-small filter-button">
          <% flag = params[:active_users] %>
          <input type="hidden" name="active_users" value="<%= flag %>" id="active_users_value"/>
          <input type="checkbox" value="<%= flag %>"<%= " checked=#{flag}" if flag %> id="active_users_checkbox_filter"/>
          <%= label_tag :active_users_checkbox_filter, t('.label_active_users') %>
        </span>
        <br />
        <%= select_tag :timestamp_user_id, options_for_select(
          @users.map{|u| [u.nickname, u.id, { 'data-active': u.active }.merge(
            @default_active_users_value && !u.active ? {disabled: true} : {})]},
          params[:timestamp_user_id])
        %>
      </div>
      <div class="col-xs-2">
        <%= label_tag :timestamp_start_at, t('.label_start') %>
        <br />
        <%= text_field_tag :timestamp_start_at, params[:timestamp_start_at], size: 14 %>
      </div>
      <div class="col-xs-2">
        <%= label_tag :timestamp_end_at, t('.label_end') %>
        <br />
        <%= text_field_tag :timestamp_end_at, params[:timestamp_end_at], size: 14 %>
      </div>
      <div class="col-xs-3 hide-checkbox">
        <% flag = params[:active_projects] %>
        <br />
        <input type="hidden" name="active_projects" value="<%= flag %>" id="active_projects_value"/>
        <input type="checkbox" value="<%= flag %>"<%= " checked=#{flag}" if flag %> id="active_projects_checkbox"/>
        <%= label_tag :active_projects_checkbox, t('.label_active_projects') %>
      </div>
      <div class="col-xs-2">
        <br />
        <%= submit_tag t('.label_submit'), class: 'btn btn-default btn-sm btn-success' %>
      </div>
    </div>
  <% end %>

<% if @timestamps.present? %>


  <!-- Nav tabs -->
  <ul class="nav nav-tabs nav-tabs-mod" role="tablist">
    <li role="presentation" class="active"><a href="#projects" data-id="projects" aria-controls="projects" role="tab" data-toggle="tab"><%= t('tabs.project') %></a></li>
    <li role="presentation"><a href="#activities" data-id="activities" aria-controls="activities" role="tab" data-toggle="tab"><%= t('tabs.activity') %></a></li>
    <li role="presentation"><a href="#table" data-id="table" aria-controls="table" role="tab" data-toggle="tab"><%= t('tabs.table') %></a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active tab-pane-mod" id="projects">
      <div class="pie-chart" id="projects-pie-chart" style="min-height: 500px; margin: 0 auto;"></div>

      <hr />

      <div class="bar-chart" id="projects-bar-chart" style="min-height: 500px; margin: 0 auto;"></div>

    </div>

    <div role="tabpanel" class="tab-pane fade tab-pane-mod" id="activities">
      <div class="pie-chart" id="activities-pie-chart" style="min-height: 500px; margin: 0 auto;"></div>

      <hr />

      <div class="bar-chart" id="activities-bar-chart" style="min-height: 500px; margin: 0 auto;"></div>

    </div>

    <div role="tabpanel" class="tab-pane fade tab-pane-mod" id="table">

      <%= render :partial => 'timestamps/table_notes' %>

    </div>
  </div>

<% else %>

  <p class="alert alert-warning">
    <%= t('.no_hours', user: @user.nickname, start: params[:timestamp_start_at], end: params[:timestamp_end_at]) %>
  </p>

<% end %>

 <% @custom_js = ["pages/summary.js"] %>